### ISSUE TITLE
Compilation on Fedora

### ISSUE THREAD

**Issue by Scafir** [jorio/Bugdom#11]
Hi,
First of all, thank you so much for this port! I have so many childhood memories with this game..
Here are the things I had to do in order to compile the game:

1. Run `dnf in freeglut-devel SDL2-devel`
2. Add the flags `-lGL -lGLU -lglut`  in CMakeLists.txt:298
3. Follow the instructions

**Comment by jorio** [comment]
Thanks! I added info about SDL2-devel for Fedora in the build instructions. Bugdom 1.3.1 also doesn't depend on glut anymore.
