### ISSUE TITLE
Getting Bugdom packaged for the official Debian/Ubuntu repositories 

### ISSUE THREAD

**Issue by github-userx** [jorio/Bugdom#13]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=989524

**Comment by jpenguin** [comment]
Here is an unofficial appimage https://download.opensuse.org/repositories/home:/jpenguin:/Games/AppImage/

**Comment by jorio** [comment]
Closing the issue because it's unlikely that Debian will ever package the game due to the license.

**Comment by khumba** [comment]
For what it's worth, I felt like putting together a Debian package, so I'm now hosting that in my personal APT repo (on my site, linked from my profile).  It's as Debian-policy-compliant as I can make it.
