### ISSUE TITLE
Does it run on Apple Silicon?

### ISSUE THREAD

**Issue by ralusek** [jorio/Bugdom#20]
And also curious regarding Mighty Mike/Power Pete.

**Comment by Frizlab** [comment]
yep it does

**Comment by jorio** [comment]
Yes, @Frizlab is right, all of the Pangea game ports run on Apple Silicon.

I'll just advise to stick with Big Sur if you can. Monterey breaks vsync in OpenGL applications, which causes a choppy framerate in the games. This also applies to Intel Macs.

**Comment by jorio** [comment]
macOS update 12.1 just came out and it fixes the vsync problem I mentioned above, so as of today there are no reservations about running the games on the latest Macs.
