### ISSUE TITLE
Bugdom 2?

### ISSUE THREAD

**Issue by teichh01** [jorio/Bugdom#21]
Any plans/permission for a Bugdom 2 port?

**Comment by jorio** [comment]
I've been taking a break from the ports lately, but I do intend to get back to it soon. I've started porting Cro-Mag Rally so I'll finish that one first. After CMR, no plans are set in stone, but Bug 2 is among the games I'd like to port eventually. We'll see!

**Comment by keithpickering** [comment]
I'll put money toward Bugdom 2. I had the original PC port when I was like 8 but it never ran properly, so I've never been able to play it

**Comment by jorio** [comment]
@teichh01 @keithpickering At last - Bugdom 2 is out! https://jorio.itch.io/bugdom2
