### ISSUE TITLE
Any way to change Windowed/Fullscreen resolutions via a menu option?

### ISSUE THREAD

**Issue by eisnerguy1** [jorio/Bugdom#25]
I was wondering if there was any way to change the resolution of the game via a menu option? I know that there is the "--fullscreen-resolution WIDTH HEIGH" command line option but, there's no option to change the resolution while in Windowed mode. Ideally, I'd love an option to have the game's resolution as 1280x960/2x scaled. Or, if that can't be done, maybe include a command line option for "--windowed-resolution WIDTH HEIGH" and also include 1280x960 as a valid option?

My main issue is that the UI just stretches while in Fullscreen mode.

Here's Windowed mode:
<img width="640" alt="Bugdom_Windowed" src="https://user-images.githubusercontent.com/3295271/170894993-57d90dc9-1c6a-4be4-8301-a2c08ca3c250.png">

And then Fullscreen mode:
![Bugdom_Fullscreen](https://user-images.githubusercontent.com/3295271/170895005-8ad74ade-d367-4034-80cd-335407da633a.png)

Thanks!

**Comment by jorio** [comment]
[Version 1.3.2](https://github.com/jorio/Bugdom/releases) has an option to constrain the viewport to a 4:3 aspect ratio in the settings.

**Comment by eisnerguy1** [comment]
Thanks! 😄
