### ISSUE TITLE
Linux build on itch.io doesn't install

### ISSUE THREAD

**Issue by jpenguin** [jorio/Bugdom#32]
for appimage to install, you must upload them using butler (tested working on private listing in my account)
`butler push ~/build/Bugdom-1.3.2-linux-x86_64.AppImage jorio/bugdom:linux-universal`

If butler doesn't work on your system or you are otherwise unable to do this, feel free to add me (tux-peng.itch.io) as an admin and I can do it for you

**Comment by jorio** [comment]
I tried it out and apparently butler zips up the appimage under the hood. It seems that you can just zip up the game and it'll work. I'll use that method for the next port that's right around the corner... and I'll fix the other games when I get around to updating them. Thanks for the heads up!

**Comment by jorio** [comment]
I just pushed the Bugdom 1.3.3 AppImage with Butler. Closing, but feel free to reopen if that didn't work.

**Comment by jpenguin** [comment]
All installed and working through Linux itch,io

Bugdom
MightyMike
Ottomatic
Nanosaur
Nanosaur II
