### ISSUE TITLE
mouse left/right seems reversed when flying a dragonfly

### ISSUE THREAD

**Issue by oresmus** [jorio/Bugdom#6]
In Level 4, while flying a dragonfly, moving the mouse left turns the flight path right, and moving the mouse right turns the flight path left. I think this differs from the original game, and I find it counterintuitive and hard to control.

(In contrast, I didn't notice any issue using the mouse in Level 3 to direct a water taxi.)

**Comment by jorio** [comment]
This behavior was inherited from the original game, but [Bugdom 1.3.3](https://github.com/jorio/Bugdom/releases) has a new setting to adjust this.
